name: albarq
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2
  

dependencies:
  flutter:
    sdk: flutter
    

  cupertino_icons: ^1.0.8
  get: ^4.7.3

  firebase_core: ^4.11.0
  firebase_auth: ^6.5.4
  cloud_firestore: ^6.6.0
  firebase_storage: ^13.4.3
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0
  url_launcher: ^6.3.2

  image_picker: ^1.2.3

  shared_preferences: ^2.5.5

  intl: ^0.20.3
  flutter_screenutil: ^5.9.3
  google_fonts: ^8.1.0
  cached_network_image: ^3.4.1

  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.8

  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.12.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/banner.jpg
    - assets/images/burger.jpg
    - assets/images/pizza.jpg