// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCettC1u9bh_wAeNKtM9-KrM843l4LsCVs',
    appId: '1:2274315162:web:478002b16092107ce9c823',
    messagingSenderId: '2274315162',
    projectId: 'albarq-tikret',
    authDomain: 'albarq-tikret.firebaseapp.com',
    storageBucket: 'albarq-tikret.firebasestorage.app',
    measurementId: 'G-2H9WLT1B5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhYhoY078jKLdpuLyICR4ZjEbOiutO4w0',
    appId: '1:2274315162:android:709112e3c283709ee9c823',
    messagingSenderId: '2274315162',
    projectId: 'albarq-tikret',
    storageBucket: 'albarq-tikret.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWtgE_v5tmm0R3hVWG6UlTuSej-dFV_Dc',
    appId: '1:2274315162:ios:117aa1c72deb9aaee9c823',
    messagingSenderId: '2274315162',
    projectId: 'albarq-tikret',
    storageBucket: 'albarq-tikret.firebasestorage.app',
    iosClientId: '2274315162-tpn9npdj0mg7tl0t1n01ejppff1sasfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.albarq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWtgE_v5tmm0R3hVWG6UlTuSej-dFV_Dc',
    appId: '1:2274315162:ios:117aa1c72deb9aaee9c823',
    messagingSenderId: '2274315162',
    projectId: 'albarq-tikret',
    storageBucket: 'albarq-tikret.firebasestorage.app',
    iosClientId: '2274315162-tpn9npdj0mg7tl0t1n01ejppff1sasfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.albarq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCettC1u9bh_wAeNKtM9-KrM843l4LsCVs',
    appId: '1:2274315162:web:3de75de07372d896e9c823',
    messagingSenderId: '2274315162',
    projectId: 'albarq-tikret',
    authDomain: 'albarq-tikret.firebaseapp.com',
    storageBucket: 'albarq-tikret.firebasestorage.app',
    measurementId: 'G-HEXJESTF85',
  );
}
